version: '3.8'
services:
  stats-server:
    build: stat/stats-server
    image: stats-server
    stdin_open: true
    tty: true
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stat-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stat-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=stat
      - SPRING_DATASOURCE_PASSWORD=stat

  stat-db:
    image: postgres:14-alpine
    container_name: stat-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=stat
      - POSTGRES_USER=stat
      - POSTGRES_DB=ewm-stats

  ewm-service:
    build: main-service
    image: main-service
    stdin_open: true
    tty: true
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - CLIENT_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/main
      - SPRING_DATASOURCE_USERNAME=main
      - SPRING_DATASOURCE_PASSWORD=main

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_PASSWORD=ewmdb
      - POSTGRES_USER=ewmdb
      - POSTGRES_DB=ewmdb
